export { default as Brand } from "./Бранд.png";
export { default as Wulfstan } from "./Вульфстен.png";
export { default as Ebba } from "./Ибба.png";
export { default as Inga } from "./Инга.png";
export { default as Ingvar } from "./Ингвар.png";
export { default as Karli } from "./Карли.png";
export { default as KingTolghar } from "./Король Толгар.png";
export { default as Rolf } from "./Рольф.png";
export { default as Svea } from "./Свея.png";
export { default as Hangvul } from "./Хангвул.png";
export { default as Helmar } from "./Хельмар.png";
export { default as Erling } from "./Эрлинг.png";
