export { default as WeakeningStrike } from "./Мучающий удар.png";
export { default as FallenKnight } from "./Падший рыцарь.png";
export { default as SealOfDarkness } from "./Печать Тьмы.png";
export { default as MasterOfPain } from "./Повелитель боли.png";
export { default as MasterOfCurses } from "./Повелитель проклятий.png";
export { default as MasterOfMind } from "./Повелитель разума.png";
export { default as CorruptedSoil } from "./Проклятая земля.png";
export { default as ShrugDarkness } from "./Слабость Тьмы.png";
export { default as DarkRenewal } from "./Тёмное восполнение.png";
