export { default as Zealot } from './Адепт.png';
export { default as Marksman } from './Арбалетчик.png';
export { default as Archangel } from './Архангел.png';
export { default as BattleGriffin } from './Боевой грифон.png';
export { default as Inquisitor } from './Инквизитор.png';
export { default as ImperialGriffin } from './Королевский грифон.png';
export { default as Squire } from './Латник.png';
export { default as Brute } from './Лендлорд.png';
export { default as Conscript } from './Ополченец.png';
export { default as Paladin } from './Паладин.png';
export { default as Vindicator } from './Ревнитель веры.png';
export { default as Champion } from './Рыцарь Изабель.png';
export { default as Seraph } from './Серафим.png';
export { default as Crossbowman } from './Стрелок.png';
