export { default as HellHound } from './Адская гончая.png';
export { default as HellCharger } from './Адский жеребец.png';
export { default as ArchDemon } from './Архидемон.png';
export { default as ArchDevil } from './Архидьявол.png';
export { default as Imp } from './Бес.png';
export { default as HornedDemon } from './Демон.png';
export { default as SuccubusMistress } from './Демонесса.png';
export { default as Devil } from './Дьявол.png';
export { default as Vermin } from './Дьяволёнок.png';
export { default as SuccubusSeducer } from './Искусительница.png';
export { default as HellStallion } from './Конь преисподней.png';
export { default as Nightmare } from './Кошмар.png';
export { default as Firehound } from './Огненная гончая.png';
export { default as HornedOverseer } from './Огненный демон.png';
export { default as PitSpawn } from './Пещерное отродье.png';
export { default as PitLord } from './Пещерный владыка.png';
export { default as PitFiend } from './Пещерный демон.png';
export { default as HornedGrunt } from './Старший демон.png';
export { default as Succubus } from './Суккуб.png';
export { default as Cerberus } from './Цербер.png';
export { default as Familiar } from './Чёрт.png';
