export { default as MagicalImmunity } from "./Антимагия.png";
export { default as DivineVengeance } from "./Божественная месть.png";
export { default as DivineStrength } from "./Божественная сила.png";
export { default as Resurrection } from "./Воскрешение.png";
export { default as Endurance } from "./Каменная кожа.png";
export { default as RighteousMight } from "./Карающий удар.png";
export { default as Regeneration } from "./Регенерация.png";
export { default as WordOfLight } from "./Святое слово.png";
export { default as Cleansing } from "./Снятие чар.png";
export { default as Teleportation } from "./Телепорт.png";
export { default as DeflectMissile } from "./Уклонение.png";
export { default as Haste } from "./Ускорение.png";
