export { default as Soulfire } from "./Взрывающиеся трупы.png";
export { default as ManaRegeneration } from "./Восполнение маны.png";
export { default as Boneward } from "./Защита нежити от магии.png";
export { default as ErraticMana } from "./Изменчивая мана.png";
export { default as Counterspell } from "./Контрзаклинание.png";
export { default as MagicInsight } from "./Мудрость.png";
export { default as Distract } from "./Отвлечение.png";
export { default as ArcaneBrillance } from "./Тайное откровение.png";
export { default as ArcaneExcellence } from "./Тайное преимущество.png";
export { default as ArcaneTraining } from "./Тайные знания.png";
export { default as WizardingProtection } from "./Чародейская защита.png";
