export { default as RuneOfBerserking } from "./Руна берсеркерства.png";
export { default as RuneOfBattleRage } from "./Руна боевой ярости.png";
export { default as RuneOfResurrection } from "./Руна воскрешения.png";
export { default as RuneOfThunderclap } from "./Руна громового раската.png";
export { default as RuneOfDragonform } from "./Руна драконьего обличья.png";
export { default as RuneOfMagicControl } from "./Руна магического надзора.png";
export { default as RuneOfEtherealness } from "./Руна неосязаемости.png";
export { default as RuneOfElementalImmunity } from "./Руна стихийной невосприимчивости.png";
export { default as RuneOfExorcism } from "./Руна экзорцизма.png";
export { default as RuneOfCharge } from "./Руна энергии.png";
