export { default as BattleLore } from "./Военное знание.png";
export { default as Stamina } from "./Выносливость.png";
export { default as Graduate } from "./Выпускник.png";
export { default as WizardsReward } from "./Колдовская награда.png";
export { default as Mentoring } from "./Менторство.png";
export { default as Bloodfire } from "./Огонь ярости.png";
export { default as LordOfTheUndead } from "./Повелитель мёртвых.png";
export { default as Intelligence } from "./Притяжение магии.png";
export { default as ArcaneIntuition} from "./Разгадка тайного.png";
export { default as TapRunes } from "./Рунный откат.png";
export { default as Scholar } from "./Учёный.png";
export { default as ArcaneExaltation } from "./Хранитель тайного.png";
