export { default as Armageddon } from "./Армагеддон.png";
export { default as StoneSpikes } from "./Каменные шипы.png";
export { default as CircleOfWinter } from "./Кольцо холода.png";
export { default as IceBolt } from "./Ледяная глыба.png";
export { default as EldritchArrow } from "./Магическая стрела.png";
export { default as MeteorShower } from "./Метеоритный дождь.png";
export { default as LightningBolt } from "./Молния.png";
export { default as Fireball } from "./Огненный шар.png";
export { default as DeepFreeze } from "./Останавливающий холод.png";
export { default as Firewall } from "./Стена огня.png";
export { default as ChainLightning } from "./Цепь молний.png";
export { default as Implosion } from "./Шок земли.png";
