export { default as Archlich } from './Архилич.png';
export { default as GhostDragon } from './Астральный дракон.png';
export { default as Banshee } from './Банши.png';
export { default as Wraith } from './Вестник смерти.png';
export { default as VampireLord } from './Высший вампир.png';
export { default as LichMaster } from './Высший лич.png';
export { default as RotZombie } from './Гниющий зомби.png';
export { default as Poltergeist } from './Дух.png';
export { default as VampirePrince } from './Князь вампиров.png';
export { default as SkeletonWarrior } from './Костяной воитель.png';
export { default as SkeletonArcher } from './Костяной лучник.png';
export { default as Spectre } from './Призрак.png';
export { default as SpectralDragon } from './Призрачный дракон.png';
export { default as PlagueZombie } from './Чумной зомби.png';
