export { default as BeginnersMagicWand } from "./Волшебная палочка новичка.png";
export { default as EdgeOfBalance } from "./Грань равновесия.png";
export { default as ArmorOfValor } from "./Доспехи бесстрашия.png";
export { default as EmeraldSlippers } from "./Изумрудные туфли.png";
export { default as TarotDeck } from "./Колода Таро.png";
export { default as RingOfTheUnrepentant } from "./Кольцо грешников.png";
export { default as RingOfLightningProtection } from "./Кольцо защиты от молний.png";
export { default as RingOfBanishment } from "./Кольцо изгнания.png";
export { default as AllSeeingCrown } from "./Корона всевидящего.png";
export { default as SwordOfMight } from "./Меч мощи.png";
export { default as SackOfEndlessGold } from "./Мешочек бесконечного золота.png";
export { default as BreastplateOfEldritchMight } from "./Нагрудник огромной мощи.png";
export { default as PhoenixFeatherCape } from "./Накидка из перьев феникса.png";
export { default as NecklaceOfTheLion } from "./Ошейник льва.png";
export { default as Wand } from "./Палочка с заклинанием.png";
export { default as CloakOfSylanna } from "./Плащ Силанны.png";
export { default as ElementalWaistband } from "./Пояс элементалей.png";
export { default as BootsOfMagicalDefense } from "./Сапоги магической защиты.png";
export { default as MagicScroll } from "./Свиток c заклинанием.png";
export { default as ManaScroll } from "./Свиток c заклинанием.png";
export { default as SextantOfTheSeaElves } from "./Секстант морских эльфов.png";
export { default as BearhideWraps } from "./Тайные защитные покровы.png";
export { default as TunicOfTheCarvedFlesh } from "./Туника из плоти.png";
export { default as FourLeafClover } from "./Четырехлистный клевер.png";
export { default as NecromancersHelm } from "./Шлем некроманта.png";
export { default as HelmOfChaos } from "./Шлем Хаоса.png";