export { default as LuckOfTheBarbarian } from "./Варварская удача.png";
export { default as DwarvenLuck } from "./Гномья удача.png";
export { default as MagicResistance } from "./Магическое сопротивление.png";
export { default as TearOfAshaVision } from "./Покровительство Асхи.png";
export { default as DeadMansCurse } from "./Смертельная неудача.png";
export { default as SoldiersLuck } from "./Солдатская удача.png";
export { default as SpoilsOfWar } from "./Трофеи.png";
export { default as Resourcefulness } from "./Удача в пути.png";
export { default as WarlocksLuck } from "./Удачливый чародей.png";
export { default as SwarmingGate } from "./Широкие врата ада.png";
export { default as ElvenLuck } from "./Эльфийская удача.png";
