export { default as LastStand } from "./Битва до последнего.png";
export { default as StandYourGround } from "./Глухая оборона.png";
export { default as Preparation } from "./Готовность.png";
export { default as DefendUsAll } from "./Защити всех нас.png";
export { default as ChillingBones } from "./Могильный холод.png";
export { default as DefensiveFormation } from "./Оборонительный хирд.png";
export { default as Hellwrath } from "./Огненное возмездие.png";
export { default as Protection } from "./Отражение.png";
export { default as PowerOfEndurance } from "./Прочность камня.png";
export { default as Resistance } from "./Сопротивление.png";
export { default as Vitality } from "./Стойкость.png";
export { default as Evasion } from "./Уклонение.png";
