export { default as Frenzy } from "./Берсерк.png";
export { default as Vampirism } from "./Вампиризм.png";
export { default as Slow } from "./Замедление.png";
export { default as Suffering } from "./Немощность.png";
export { default as CurseOfTheNetherworld } from "./Нечестивое слово.png";
export { default as Weakness } from "./Ослабление.png";
export { default as Blindness } from "./Ослепление.png";
export { default as PuppetMaster } from "./Подчинение.png";
export { default as Vulnerability } from "./Разрушающий луч.png";
export { default as Confusion } from "./Рассеянность.png";
export { default as Sorrow } from "./Скорбь.png";
export { default as Decay } from "./Чума.png";
