export { default as Assassin } from './Ассасин.png';
export { default as ShadowMatriarch } from './Владычица тени.png';
export { default as RedDragon } from './Красный дракон.png';
export { default as Stalker } from './Ловчий.png';
export { default as BloodSister } from './Мегера.png';
export { default as MinotaurTaskmaster } from './Минотавр-надсмотрщик.png';
export { default as MinotaurGuard } from './Минотавр-страж.png';
export { default as DeepHydra } from './Пещерная гидра.png';
export { default as BriskRaider } from './Проворный наездник.png';
export { default as FoulHydra } from './Тёмная гидра.png';
export { default as GrimRaider } from './Тёмный всадник.png';
export { default as BloodFury } from './Фурия.png';
export { default as ShadowMistress } from './Хозяйка ночи.png';
export { default as BlackDragon } from './Чёрный дракон.png';
