export { default as ForgottenHeroArmorIcon } from "./Доспехи Забытого Героя.png";
export { default as BreastplateOfTheDwarfKingIcon } from "./Кираса короля гномов.png";
export { default as RingOfSarIssaIcon } from "./Кольцо Сар-Иссы.png";
export { default as RingOfSwiftnessIcon } from "./Кольцо стремительности.png";
export { default as LeadershipCrownIcon } from "./Корона лидерства.png";
export { default as LionCrownIcon } from "./Корона льва.png";
export { default as CrownOfSarIssaIcon } from "./Корона Сар-Иссы.png";
export { default as PendantOfIcyEmbraceIcon } from "./Кулон ледяных обьятий.png";
export { default as PendantOfAbsorptionIcon } from "./Кулон Поглощения.png";
export { default as UnicornHornBowIcon } from "./Лук из рога Единорога.png";
export { default as BloodClawNecklaceIcon } from "./Ожерелье Кровавого Когтя.png";
export { default as DeadlyShadowCloakIcon } from "./Плащ Смертоносной Тени.png";
export { default as LeggingsOfTheDwarfKingIcon } from "./Поножи короля гномов.png";
export { default as StaffOfTheUnderworldIcon } from "./Посох Преисподней.png";
export { default as StaffOfSarIssaIcon } from "./Посох Сар-Иссы.png";
export { default as SaintsSandalsIcon } from "./Сандалии Святого.png";
export { default as WanderersBootsIcon } from "./Сапоги странника.png";
export { default as VolumeOfSummoningMagicIcon } from "./Том магии Призыва.png";
export { default as LightMagicVolumeIcon } from "./Том магии Света.png";
export { default as VolumeOfDarkMagicIcon } from "./Том магии Тьмы.png";
export { default as ChaosMagicVolumeIcon } from "./Том магии Хаоса.png";
export { default as TridentOfTheTitansIcon } from "./Трезубец Титанов.png";
export { default as RobeOfSarIssaIcon } from "./Халат Сар-Иссы.png";
export { default as MarkelsSkullIcon } from "./Череп Маркела.png";
export { default as HelmOfTheDwarfKingIcon } from "./Шлем короля гномов.png";
export { default as DwarfKingsShieldIcon } from "./Щит короля гномов.png";
