export { default as AmuletOfNecromancy } from "./Амулет некроманта.png";
export { default as ArmorOfTheForgottenHero } from "./Доспехи Забытого Героя.png";
export { default as ShacklesOfTheLastMan } from "./Кандалы неизбежности.png";
export { default as CuirassOfTheDwarvenKings } from "./Кираса короля гномов.png";
export { default as RingOfMachineAffinity } from "./Кольцо родства с машинами.png";
export { default as RingOfSarIssus } from "./Кольцо Сар-Иссы.png";
export { default as RingOfSpeed } from "./Кольцо скорости.png";
export { default as RingOfCelerity } from "./Кольцо стремительности.png";
export { default as CrownOfLeadership } from "./Корона лидерства.png";
export { default as LionCrown } from "./Корона льва.png";
export { default as CrownOfSarIssus } from "./Корона Сар-Иссы.png";
export { default as WingsOfTheAngel } from "./Крылья ангела.png";
export { default as EvercoldIcicle } from "./Кулон ледяных объятий.png";
export { default as PendantOfMastery } from "./Кулон Мастерства.png";
export { default as PendantOfConflux } from "./Кулон Поглощения.png";
export { default as UnicornHornBow } from "./Лук из рога Единорога.png";
export { default as MaskOfEquity } from "./Маска справедливости.png";
export { default as NecklaceOfTheBloodyClaw } from "./Ожерелье Кровавого Когтя.png";
export { default as SandrosCloak } from "./Плащ Сандро.png";
export { default as CloakOfDeathsShadow } from "./Плащ Смертоносной Тени.png";
export { default as GreavesOfTheDwarvenKings } from "./Поножи короля гномов.png";
export { default as StaffOfTheNetherworld } from "./Посох Преисподней.png";
export { default as StaffOfSarIssus } from "./Посох Сар-Иссы.png";
export { default as SandalsOfTheBlessed } from "./Сандалии Святого.png";
export { default as BootsOfLevitation } from "./Сапоги Левитации.png";
export { default as WindstriderBoots } from "./Сапоги странника.png";
export { default as TearOfAsha } from "./Слеза Асхи.png";
export { default as TomeOfSummoningMagic } from "./Том магии Призыва.png";
export { default as TomeOfLightMagic } from "./Том магии Света.png";
export { default as TomeOfDarkMagic } from "./Том магии Тьмы.png";
export { default as TomeOfDestruction } from "./Том магии Хаоса.png";
export { default as TridentOfTheTitans } from "./Трезубец Титанов.png";
export { default as RobeOfSarIssus } from "./Халат Сар-Иссы.png";
export { default as SkullOfMarkal } from "./Череп Маркела.png";
export { default as HelmOfTheDwarvenKings } from "./Шлем короля гномов.png";
export { default as ShieldOfTheDwarvenKings } from "./Щит короля гномов.png";