export { default as GnomishSmithyHammerIcon } from "./Гномий кузнечный молот.png";
export { default as DragonscaleArmorIcon } from "./Доспехи из чешуи дракона.png";
export { default as OgresCudgelIcon } from "./Дубина людоеда.png";
export { default as GoldenHorseshoeIcon } from "./Золотая подкова.png";
export { default as MarvelousQuiverIcon } from "./Изумительный колчан.png";
export { default as DragonEyeRingIcon } from "./Кольцо Глаз дракона.png";
export { default as LifeForceRingIcon } from "./Кольцо жизненной силы.png";
export { default as RingOfCautionIcon } from "./Кольцо предостережения.png";
export { default as BrokenSpiritRingIcon } from "./Кольцо сломленного духа.png";
export { default as DragonsClawCrownIcon } from "./Корона из когтей дракона.png";
export { default as IceShieldIcon } from "./Ледяной щит.png";
export { default as MoonBladeIcon } from "./Лунный клинок.png";
export { default as DragonwingMantleIcon } from "./Мантия из крыльев дракона.png";
export { default as LionManeCapeIcon } from "./Накидка с гривой льва.png";
export { default as DragonTeethNecklaceIcon } from "./Ожерелье из зубов дракона.png";
export { default as VictoryNecklaceIcon } from "./Ожерелье победы.png";
export { default as FlameDragonTongueIcon } from "./Пламенный язык дракона.png";
export { default as DragonboneLeggingsIcon } from "./Поножи из кости дракона.png";
export { default as CursedRingIcon } from "./Проклятое кольцо.png";
export { default as RunedWarHarnessIcon } from "./Рунная боевая упряжь.png";
export { default as RunedBattleAxIcon } from "./Рунный боевой топор.png";
export { default as AxOfTheMountainKingIcon } from "./Секира горного короля.png";
export { default as VolumeOfForceIcon } from "./Том Силы.png";
export { default as DragonscaleShieldIcon } from "./Щит из чешуи дракона.png";
export { default as CannibalShieldIcon } from "./Щит людоеда.png";
