export { default as DwarvenSmithyHammer } from "./Гномий кузнечный молот.png";
export { default as DragonScaleArmor } from "./Доспехи из чешуи дракона.png";
export { default as OgreClub } from "./Дубина людоеда.png";
export { default as GoldenHorseshoe } from "./Золотая подкова.png";
export { default as TreebornQuiver } from "./Изумительный колчан.png";
export { default as DragonEyeRing } from "./Кольцо Глаз дракона.png";
export { default as RingOfVitality } from "./Кольцо жизненной силы.png";
export { default as RingOfCaution } from "./Кольцо предостережения.png";
export { default as RingOfTheBrokenWill } from "./Кольцо сломленного духа.png";
export { default as ScaleMailOfEnlightenment } from "./Кольчуга просвещенности.png";
export { default as DragonTalonCrown } from "./Корона из когтей дракона.png";
export { default as ShieldOfCrystalIce } from "./Ледяной щит.png";
export { default as Moonblade } from "./Лунный клинок.png";
export { default as DragonWingMantle } from "./Мантия из крыльев дракона.png";
export { default as CapeOfTheLionsMane } from "./Накидка с гривой льва.png";
export { default as DragonTeethNecklace } from "./Ожерелье из зубов дракона.png";
export { default as NecklaceOfVictory } from "./Ожерелье победы.png";
export { default as DragonFlameTongue } from "./Пламенный язык дракона.png";
export { default as DragonBoneGreaves } from "./Поножи из кости дракона.png";
export { default as CursedRing } from "./Проклятое кольцо.png";
export { default as HornOfPlenty } from "./Рог изобилия.png";
export { default as RuneOfFlame } from "./Руна пламени.png";
export { default as RunicWarHarness } from "./Рунная боевая упряжь.png";
export { default as RunicWarAxe } from "./Рунный боевой топор.png";
export { default as BootsOfTheOpenRoad } from "./Сапоги открытого пути.png";
export { default as BootsOfTheSwiftJourney } from "./Сапоги путешественника.png";
export { default as AxeOfTheMountainLords } from "./Секира горного короля.png";
export { default as BagOfEndlessGold } from "./Сума бесконечного золота.png";
export { default as BookOfPower } from "./Том Силы.png";
export { default as TurbanOfEnlightenment } from "./Тюрбан просвещенности.png";
export { default as DragonScaleShield } from "./Щит из чешуи дракона.png";
export { default as OgreShield } from "./Щит людоеда.png";
