export { default as Banish } from "./Изгнание.png";
export { default as HauntedMines } from "./Обитаемые шахты.png";
export { default as FireWarriors } from "./Огненные воины.png";
export { default as MasterOfLife } from "./Повелитель жизни.png";
export { default as MasterOfConjuration } from "./Повелитель чар.png";
export { default as RunicArmour } from "./Рунный щит.png";
export { default as ElementalBalance } from "./Стихийное равновесие.png";
export { default as FogVeil } from "./Туманная завеса.png";
export { default as MasterOfEarthblood } from "./Хозяин земли.png";
export { default as Exorcism } from "./Экзорцизм.png";
