export { default as FistOfWrath } from "./Волшебный кулак.png";
export { default as Earthquake } from "./Землетрясение.png";
export { default as ArcaneCrystal } from "./Кристалл тайного.png";
export { default as ArcaneArmor } from "./Небесный щит.png";
export { default as FireTrap } from "./Огненная ловушка.png";
export { default as RaiseDead } from "./Поднятие мертвых.png";
export { default as WaspSwarm } from "./Призыв осиного роя.png";
export { default as SummonHive } from "./Призыв улья.png";
export { default as ConjurePhoenix } from "./Призыв феникса.png";
export { default as SummonElementals } from "./Призыв элементалей.png";
export { default as PhantomForces } from "./Создание фантома.png";
export { default as BladeBarrier } from "./Стена мечей.png";
