export { default as CentaurMarauder } from './Боевой кентавр.png';
export { default as Warmonger } from './Вармонгер.png';
export { default as Chieftain } from './Вожак.png';
export { default as EarthDaughter } from './Дочерь земли.png';
export { default as SkyDaughter } from './Дочерь неба.png';
export { default as GoblinWitchDoctor } from './Колдун гоблинов.png';
export { default as CentaurNomad } from './Кочевой кентавр.png';
export { default as BloodeyedCyclops } from './Кровоглазый циклоп.png';
export { default as Mauler } from './Орочий боец.png';
export { default as Executioner } from './Палач.png';
export { default as Paokai } from './Паокай.png';
export { default as UntamedCyclops } from './Свободный циклоп.png';
export { default as GoblinTrapper } from './Траппер.png';
export { default as FoulWyvern } from './Тёмная виверна.png';
