export { default as Ballista } from "./Баллиста.png";
export { default as RemoteControl } from "./Власть над машинами.png";
export { default as ImbueBallista } from "./Заколдованная баллиста.png";
export { default as Catapult } from "./Катапульта.png";
export { default as FirstAid } from "./Первая помощь.png";
export { default as GoblinSupport } from "./Помощь гоблинов.png";
export { default as RunicMachines } from "./Рунные машины.png";
export { default as BrimstoneRain } from "./Серный дождь.png";
export { default as TripleBallista } from "./Скорострельная баллиста.png";
export { default as Tremors } from "./Сотрясение земли.png";
export { default as AmmoCart } from "./Тележка с боеприпасами.png";
export { default as PlagueTent } from "./Чумная палатка.png";
export { default as AmmoCart } from "./Тележка с боеприпасами.png";
